trigger:
  branches: 
    include:
    - master
  tags:
    include:
    - '*'
pr:
  branches:
    include:
    - '*'

stages:
- stage: static_checks
  displayName: Static Checks
  dependsOn: []
  jobs:
  - job:
    displayName: 'Typechecking'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - script: |
        python -m pip install -U mypy==0.730
        mypy clkhash --ignore-missing-imports --no-implicit-optional --disallow-untyped-calls
      displayName: 'mypy (pinned)'

    - script: |
        python -m pip install types-pkg_resources
        python -m pip install -U mypy
        mypy clkhash --ignore-missing-imports --no-implicit-optional --disallow-untyped-calls
      displayName: 'mypy (latest)'
      continueOnError: true

  - job:
    displayName: "Check Git Tags"
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
  # In this step, if this build is triggered by a tag, it will add a tag 'Automated' to the current build.
    - script: echo "##vso[build.addbuildtag]Automated"
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

- stage: build_and_test
  displayName: Build and Test
  dependsOn: []
  jobs:
  - template: .azurePipeline/wholeBuild.yml  # Template reference
    parameters:
      pythonVersions: ['3.6', '3.7', '3.8', '3.9']
      operatingSystems: ['vs2017-win2016']
      architectures: ['x86', 'x64']
  - template: .azurePipeline/wholeBuild.yml  # Template reference
    parameters:
      pythonVersions: ['3.6', '3.7', '3.8', '3.9']
      operatingSystems: ['macos-10.14']
      architectures: ['x64']
  - template: .azurePipeline/wholeBuild.yml  # Template reference
    parameters:
      pythonVersions: ['3.6', '3.7', '3.8', '3.9', 'pypy3']
      operatingSystems: ['ubuntu-18.04']
      architectures: ['x64']
  - job:
    displayName: 'Package Source Distribution'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
      displayName: 'Init Python'
    - script: |
        python -m pip install -U pip
    - script: python setup.py sdist
      displayName: 'Package sdist'
    - task: PublishPipelineArtifact@1
      inputs:
        artifact: 'sdist'
        targetPath: 'dist/'

- stage: package
  displayName: Package Artifacts
  dependsOn: ['build_and_test']
  jobs:
  - job:
    displayName: 'Package Artifacts'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        path: $(Pipeline.Workspace)

    - script: |
        cd $(Pipeline.Workspace)
        mkdir artifacts
        mv vs2017-win2016-3.7-x64/*.exe artifacts
        mv vs2017-win2016-3.7-x86/*.exe artifacts
        mv ubuntu-18.04-3.7-x64/*.whl artifacts
        mv sdist/* artifacts
        ls artifacts
      displayName: 'List Artifacts'
    - task: PublishPipelineArtifact@1
      inputs:
        artifact: 'release'
        targetPath: '$(Pipeline.Workspace)/artifacts'
