parameters:
  pythonVersions: []
  operatingSystems: []
  architectures: []

jobs:
- job: 'test_and_publish'
  strategy:
    matrix:
      ${{ each py in parameters.pythonVersions }}:
        ${{ each os in parameters.operatingSystems }}:
          ${{ each architecture in parameters.architectures }}:
            ${{ format('Python {0} on {1} ({2})', py, os, architecture) }}:
              pythonVersion: ${{ py }}
              operatingSystem: ${{ os }}
              architecture: ${{ architecture }}

  pool:
    vmImage: $(operatingSystem)

  displayName: 'Unittest - '

  steps:
# I would not have found on my own such a step. Thanks https://dvlup.com/2019/01/03/using-powershell-to-installing-msi-in-a-devops-build/
# The solution I found was not working: it hanged forevever, using "msiexec /i"
# These steps are required because of at least the bitarray dependency (but maybe more). See issue #153 tracking if bitarray is still used.
  - powershell: Invoke-WebRequest -Uri https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -OutFile VCForPython27.msi
    displayName: 'Download Microsoft Visual C++ 9.0 from https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi'
    condition: eq(variables['pythonVersion'], 2.7)
  - powershell: Start-Process VCForPython27.msi -ArgumentList "/q" -Wait 
    displayName: 'Install Microsoft Visual C++ 9.0.'
    condition: and(eq(variables['operatingSystem'], 'vs2017-win2016'), eq(variables['pythonVersion'], 2.7))

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: '$(architecture)'

  - script: |
      python -m pip install -U pip
      python -m pip install -U wheel setuptools codecov
      python -m pip install -U -r requirements.txt
    displayName: 'Install requirements'
    
  - script: python setup.py bdist_wheel
    displayName: 'Package wheels'

  - script: python -m pytest --cov=clkhash --junitxml=testResults.xml --cov-report=xml:coverageReport.xml --cov-report=html:htmlcov
    displayName: 'Test with pytest'
    timeoutInMinutes: 10 # it should pass in 2.5 minutes, so 10 should be more than enough even if the server is busy.
    env:
      INCLUDE_CLI: 1
      TEST_ENTITY_SERVICE: https://testing.es.data61.xyz
  
  # If we are running on a Windows machine, only the tutorials which are not using anonlink can be run, otherwise
  # all the tutorials should be run.
  # The list of tutorials without anonlink are provided in the file `docs/list_tutorials_without_anonlink.txt`.
  # The anonlink requirement is in its own dependency file `docs/doc-requirements-anonlink.txt` while all
  # the other required dependencies are in `docs/doc-requirements-others.txt`.
  # Note also that with the current requirements, 
  - script: |
      python -m pip install -U -r docs/doc-requirements-anonlink.txt -r docs/doc-requirements-others.txt
      pytest --nbval docs -x --sanitize-with docs/tutorial_sanitize.cfg
    displayName: 'Test all notebooks'
    condition: and(ne(variables['operatingSystem'], 'vs2017-win2016'), ne(variables['pythonVersion'], '2.7'))
  # This step currently fails. Cf issue #287 https://github.com/data61/clkhash/issues/287
  #- bash: |
  #    python -m pip install -U -r docs/doc-requirements-others.txt
  #    list_file=''
  #    for file in $(cat docs/list_tutorials_without_anonlink.txt)
  #    do
  #      list_file="$list_file docs/$file"
  #    done
  #    pytest --nbval -x --sanitize-with docs/tutorial_sanitize.cfg $list_file
  #  displayName: 'Test notebooks without anonlink'
  #  condition: and(eq(variables['operatingSystem'], 'vs2017-win2016'), ne(variables['pythonVersion'], '2.7'))

  - task: PublishTestResults@2
    displayName: 'Publish test results in Azure'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'testResults.xml'
      testRunTitle: 'Test results on a vm $(operatingSystem) ($(architecture)) for Python $(pythonVersion)'
      failTaskOnFailedTests: true

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage in Azure'
    # If the previous stage fail, we still want to run this one as the previous stage may fail because of a failing test.
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverageReport.xml'
      failIfCoverageEmpty: true

  - script: python -m codecov --token $(CODECOV_TOKEN) --file coverageReport.xml
    displayName: 'Send coverage to codecov'
    condition: succeededOrFailed()

  - script: |
      pyinstaller cli.spec
      .\dist\clkutil.exe --version
      mv .\dist\clkutil.exe .\dist\clkutil-x64.exe
    displayName: 'Build clkutil-x86.exe'
    condition: and(eq(variables['operatingSystem'], 'vs2017-win2016'), eq(variables['pythonVersion'], '3.7'), eq(variables['architecture'], 'x86'))

  - script: |
      pyinstaller cli.spec
      .\dist\clkutil.exe --version
      mv .\dist\clkutil.exe .\dist\clkutil-x64.exe
    displayName: 'Build clkutil-x64.exe'
    condition: and(eq(variables['operatingSystem'], 'vs2017-win2016'), eq(variables['pythonVersion'], '3.7'), eq(variables['architecture'], 'x64'))

  # Note PipelineArtifacts replace BuildArtifacts
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifacts in Azure'
    condition: and( eq(variables['operatingSystem'], 'vs2017-win2016'), eq(variables['pythonVersion'], '3.7'))
    inputs:
      artifact: 'Build Artifacts ${{ parameters.operatingSystem }} for Python ${{ parameters.pythonVersion }}'
      targetPath: 'dist/(*.exe|*.whl)'
