# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Testing

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  unittests:
    name: Unittests ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]
        exclude:
          - os: macos-latest
            python: "pypy-3.8"
          - os: windows-latest
            python: "pypy-3.8"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt

      - name: Build and install clkhash
        shell: bash
        run: |
          python -m pip install -e .

      - name: Test with pytest
        run: |
          pytest --cov=clkhash --cov-report=xml:coverage.xml -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-clkhash

  notebooktests:
    name: Notebook tests ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r docs/doc-requirements.txt

      - name: Build and install clkhash
        shell: bash
        run: python -m pip install -e .

      - name: Test notebooks
        shell: bash
        run: pytest --nbval docs -x --sanitize-with docs/tutorial_sanitize.cfg
